#!/usr/bin/env bash
#script that displays the listening ports along with the PID 

listening_sockets=$(ss -tlnp)

while IFS= read -r line; do
  pid=$(echo "$line" | awk '{print $NF}' | awk -F '[=/]' '{print $2}')
  port=$(echo "$line" | awk '{print $4}' | awk -F ':' '{print $NF}')
  program=$(basename "$(readlink -f "/proc/$pid/exe")")

  echo "PID: $pid, Program: $program, Port: $port"

done <<< "$listening_sockets"
